name: Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ github.token }}
      - name: Install prerequisites
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y texlive latexmk texlive-formats-extra texlive-fonts-extra
      - name: Build pdf
        run: pdflatex SakuGlumoff.tex
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: SakuGlumoff.pdf
          if-no-files-found: error
  release:
    needs: [build]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pdf
          path: artifacts
      - name: Create a release
        run: |
          RELEASE_VERSION="$(echo ${GITHUB_REF_NAME} | cut -f1 -d-)"
          gh release create ${GITHUB_REF_NAME} \
            --title ${RELEASE_VERSION} \
            --draft
          gh release upload ${GITHUB_REF_NAME} artifacts/* --clobber
